export const COUNTRIES = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Japan",
  "Singapore",
  "United Arab Emirates",
  "Switzerland",
  "Netherlands",
  "Brazil",
  "India",
  "South Korea",
  "Mexico",
  "Spain",
  "Italy",
  "Nigeria",
  "South Africa",
  "Other",
] as const;
